//Problem 2
//Each new term in the Fibonacci sequence is generated by adding the 
//previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not 
//exceed four million, find the sum of the even-valued terms.

public class Euler002 {
	public static void main(String[] args) {
		int sum = 0, term1 = 1, term2 = 1, term3 = 2;
		
		//progresses through the Fibonacci sequence, adding 
		//every 3rd term (just the even terms) to the sum,
		//until the terms are larger than 4 million
		do{
			sum += term3;
			term1 = term2 + term3;
			term2 = term3 + term1; 
			term3 = term1 + term2;			
		}while(term3 < 4000000);
		System.out.println(sum);
	}
}
